apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: api-image-policy
spec:
  images:
    - glob: "ghcr.io/*/w10-api*"
  authorities:
    - key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1nuEAn5c04888CUSXq0hyUQRECEj
          JtWDg7jqsHU9d3g/zmDvaME3rMxepz8OIV4EjLyeGEbF0hHZgGN476WFmg==
          -----END PUBLIC KEY-----
