apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: api-image-policy
spec:
  images:
    - glob: "ghcr.io/*/w10-api*"
  authorities:
    - key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE9m+9Y5o53F8aXq3/QoB2j0kU2QO8
          1Z7R0t8509y3/QoB2j0kU2QO81Z7R0t8509y3/QoB2j0kU2QO81Z7R0t8509y3
          [DÁN NỘI DUNG COSIGN.PUB CỦA BẠN VÀO ĐÂY]
          -----END PUBLIC KEY-----
