apiVersion: v1
kind: Pod
metadata:
  name: test-pod-latest
  namespace: demo
spec:
  containers:
  - name: test
    image: nginx:latest
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
