apiVersion: v1
kind: Pod
metadata:
  name: test-pod-root
  namespace: demo
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: test
    image: nginx:1.25.1
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
