apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: api-success-rate
  namespace: argocd-test
spec:
  metrics:
  - name: success-rate
    interval: 15s
    successCondition: len(result) == 0 or result[0] >= 0.95
    failureLimit: 5
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          (sum(rate(flask_http_request_total{namespace="argocd-test", status!~"5.."}[1m])) or vector(1))
          /
          (sum(rate(flask_http_request_total{namespace="argocd-test"}[1m])) or vector(1))
