apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
  namespace: argocd-test
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: argocd-test-backend:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: ERROR_RATE
          value: "0.5"
        - name: VERSION
          value: "v3"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
  strategy:
    canary:
      analysis:
        templates:
        - templateName: api-success-rate
      steps:
      - setWeight: 25
      - pause: { duration: 1m }
      - setWeight: 50
      - pause: { duration: 1m }
      - setWeight: 100
